version: '3.7'

services:
  websocket:
    build: .
    container_name: websocket
    network_mode: jobber
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    command: npm start
